/**
 * @module MutationTypes
 * 
 * @description En este fichero se encuentran las macros correspondientes con cada uno de los tipos de mutaciones que existen en el sistema
 */

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE'

export const CHANGE_INFO_SUCCESS = 'CHANGE_INFO_SUCCESS'
export const CHANGE_INFO_FAILURE = 'CHANGE_INFO_FAILURE'

export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE'

export const FETCH_IMAGES_REQUEST = 'FETCH_IMAGES_REQUEST'
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS'
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE'

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE'

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE'

export const GEN_SOUNDSCAPE_REQUEST = 'GEN_SOUNDSCAPE_REQUEST'
export const GEN_SOUNDSCAPE_SUCCESS = 'GEN_SOUNDSCAPE_SUCCESS'
export const GEN_SOUNDSCAPE_FAILURE = 'GEN_SOUNDSCAPE_FAILURE'

export const ADD_USER_CONTRIBUTOR = 'ADD_USER_CONTRIBUTOR'
export const ADD_SHEET_CONTRIBUTOR = 'ADD_SHEET_CONTRIBUTOR'
export const ADD_COLLECTION_CONTRIBUTOR = 'ADD_COLLECTION_CONTRIBUTOR'
export const ADD_SHEET_CREATOR = 'ADD_SHEET_CREATOR'
export const ADD_COLLECTION_CREATOR = 'ADD_COLLECTION_CREATOR'

export const REMOVE_USER_CONTRIBUTOR = 'REMOVE_USER_CONTRIBUTOR'
export const REMOVE_SHEET_CONTRIBUTOR = 'REMOVE_SHEET_CONTRIBUTOR'
export const REMOVE_COLLECTION_CONTRIBUTOR = 'REMOVE_COLLECTION_CONTRIBUTOR'
export const REMOVE_SHEET_CREATOR = 'REMOVE_SHEET_CREATOR'
export const REMOVE_COLLECTION_CREATOR = 'REMOVE_COLLECTION_CREATOR'

export const SAVE_COLLECTION_DATE = 'SAVE_COLLECTION_DATE'
export const SAVE_SHEET_DATE = 'SAVE_SHEET_DATE'
export const SAVE_USER_DATE = 'SAVE_USER_DATE'

export const UPLOAD_COLLECTION_REQUEST = 'UPLOAD_COLLECTION_REQUEST'
export const UPLOAD_COLLECTION_SUCCESS = 'UPLOAD_COLLECTION_SUCCESS'
export const UPLOAD_COLLECTION_FAILURE = 'UPLOAD_COLLECTION_FAILURE'

export const UPLOAD_PIECE_REQUEST = 'UPLOAD_PIECE_REQUEST'
export const UPLOAD_PIECE_SUCCESS = 'UPLOAD_PIECE_SUCCESS'
export const UPLOAD_PIECE_FAILURE = 'UPLOAD_PIECE_FAILURE'

export const ADD_NEW_ITEM_REQUEST = 'ADD_NEW_ITEM_REQUEST'
export const ADD_NEW_ITEM_SUCCESS = 'ADD_NEW_ITEM_SUCCESS'
export const ADD_NEW_ITEM_FAILURE = 'ADD_NEW_ITEM_FAILURE'
