"""empty message

Revision ID: 34f3a20c806b
Revises: b6a8ce3d6a6c
Create Date: 2023-08-30 11:42:45.432300

"""
from alembic import op
import sqlalchemy as sa


revision = '34f3a20c806b'
down_revision = 'b6a8ce3d6a6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###