"""empty message

Revision ID: 8964b67bca8e
Revises: 1e5b445ac946
Create Date: 2023-09-06 20:44:27.466129

"""
from alembic import op
import sqlalchemy as sa


revision = '8964b67bca8e'
down_revision = '1e5b445ac946'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.alter_column('midi',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.alter_column('midi',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###