"""empty message

Revision ID: 96add3443b52
Revises: 8964b67bca8e
Create Date: 2023-09-06 20:48:59.373952

"""
from alembic import op
import sqlalchemy as sa


revision = '96add3443b52'
down_revision = '8964b67bca8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.add_column(sa.Column('midi_obj', sa.LargeBinary(), server_default=sa.text("''::bytea"), nullable=True))
        batch_op.drop_column('midi')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.add_column(sa.Column('midi', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('midi_obj')

    # ### end Alembic commands ###