"""empty message

Revision ID: 96e66e45bcff
Revises: 443551eaab75
Create Date: 2023-10-11 13:38:19.645556

"""
from alembic import op
import sqlalchemy as sa


revision = '96e66e45bcff'
down_revision = '443551eaab75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece_col', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece_col', schema=None) as batch_op:
        batch_op.drop_column('code')
        batch_op.drop_column('review')

    # ### end Alembic commands ###