"""empty message

Revision ID: a4b84212d871
Revises: fde9da1f3363
Create Date: 2023-08-29 10:07:09.996692

"""
from alembic import op
import sqlalchemy as sa


revision = 'a4b84212d871'
down_revision = 'fde9da1f3363'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.drop_column('review')

    # ### end Alembic commands ###