"""empty message

Revision ID: b4d6181c0837
Revises: b4357af567f2
Create Date: 2023-08-29 11:42:26.809814

"""
from alembic import op
import sqlalchemy as sa


revision = 'b4d6181c0837'
down_revision = 'b4357af567f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###