"""empty message

Revision ID: bda522bd5bbb
Revises: 
Create Date: 2023-07-24 16:08:43.939860

"""
from alembic import op
import sqlalchemy as sa


revision = 'bda522bd5bbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###