"""empty message

Revision ID: dada38a05768
Revises: a4b84212d871
Create Date: 2023-08-29 11:18:47.949828

"""
from alembic import op
import sqlalchemy as sa


revision = 'dada38a05768'
down_revision = 'a4b84212d871'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###