"""empty message

Revision ID: fde9da1f3363
Revises: bda522bd5bbb
Create Date: 2023-07-26 10:04:22.353962

"""
from alembic import op
import sqlalchemy as sa


revision = 'fde9da1f3363'
down_revision = 'bda522bd5bbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###